# Generated by Django 3.2.6 on 2021-08-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTheme',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код урока')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('grade', models.IntegerField(verbose_name='Оценка темы')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код теста')),
                ('question_count', models.IntegerField(verbose_name='количество вопросов')),
                ('content', models.TextField(verbose_name='Контент')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('specialization', models.CharField(max_length=150, verbose_name='Специализация')),
                ('curator', models.ForeignKey(default='Нет куратора', max_length=150, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studwork.teacher', verbose_name='Куратор')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('administrator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studwork.teacher', verbose_name='Администратор')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('s', 'Обычный'), ('k', 'Контрольный')], default='s', max_length=1, verbose_name='Обычный/контрольный')),
                ('lesson_time', models.TimeField(verbose_name='Время урока')),
                ('lesson_date', models.DateField(verbose_name='Дата урока')),
                ('is_done', models.BooleanField(verbose_name='Проведен')),
                ('right_answers', models.IntegerField(verbose_name='Количество правильных ответов')),
                ('lesson_themes', models.ManyToManyField(related_query_name='themes', to='studwork.LessonTheme', verbose_name='Темы')),
                ('test', models.ManyToManyField(related_query_name='test', to='studwork.Test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Название курса')),
                ('course_grade', models.IntegerField(verbose_name='Оценка')),
                ('test', models.ManyToManyField(related_query_name='plan_to_test', to='studwork.Test', verbose_name='Тест')),
                ('themes', models.ManyToManyField(related_query_name='themes', to='studwork.LessonTheme', verbose_name='Темы')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер договора')),
                ('count_paid_lessons', models.IntegerField(verbose_name='Количество купленных уроков')),
                ('contract_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заключения')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='course', to='studwork.courseplan', verbose_name='Курс')),
                ('lessons', models.ManyToManyField(related_query_name='lesson', to='studwork.Lesson', verbose_name='Уроки')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='parent', to='studwork.parent', verbose_name='Родитель')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='student', to='studwork.student', verbose_name='Ученик')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='teacher', to='studwork.teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
